apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-ci-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-ci-cd
  template:
    metadata:
      labels:
        app: test-ci-cd
    spec:
      containers:
        - name: test-ci-cd
          image: chinwan1/cicd-test-api:latest-dev
          ports:
            - containerPort: 80