apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-ci-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-ci-cd
  template:
    metadata:
      labels:
        app: test-ci-cd
    spec:
      containers:
        - name: test-ci-cd
          image: asia-southeast1-docker.pkg.dev/poc-other-432010/cicd-repo/test-ci-cd:v.1.0.1
          ports:
            - containerPort: 80