---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appsecret
  namespace: default
spec:
  encryptedData:
    apikey: AgAq4GjuLCwgPjhUOmxdzdBIGITPIDxYk328Yim7uvo+cYF46QenJUVyMVt9iSj57cqQArsM+BVMKDFjRpgDxTeSNDLJOIi0yNYHKQJdAruL9zxDefT3L5OeFnr7psei8/X3bsAnkdciRtqsN1J8TBlRjy3WU1wgo2Kzb2r1qG6gmBj2VUZQtqI2UkgM9dygm5+CZvirBk470T4+lUpPtlaw01dpXMCTLvoQpI5iiyGD1PSthSMMI30MFiA4ToFeAKxJtCndBrAXTA0IPki29FSzl/MiNUKgjoLMFHflpR9SZVQkNy8v6AwDMYSje3C83P4SKRV/UgNgaNufjR9fTyKEJUOYBIP2Xvavy0iNwupmEy8+04mtpDOUM3DyvC2KWAzRMT4lJ0MjQ8HMK33ik27o5Y5VQAAAfG2ThoATXanlYMgLbgQGElRJvCaq71i6G61s1hqjVF3gvkd1fHfDPwHOt/GVSsSVx1fMlZjbvcPLtGhDwSdsTW4ND0lV7b+3wtPNmGKjqYO5so06fmuWHZQSdhApTi1nXbENXZRzy1mWiukhYK4ubA8/70Qws7S6dITZ/tHVWP36FbHWfgyB02UUM2JM/30w/Mxi5ldu0K9NPDlfu5ZxOSzAtc7VejlC9auAn3Dlo6L2agwYNk60ppHO87JoajzCWGx6r19Y7AB475njyr5d2eV0/Dqy/r7MpNhr5QrBuRxOFRL3SZU+2JJoJB0A2XUnT66gedrNnN3F/Z3N9ireAg==
  template:
    metadata:
      creationTimestamp: null
      name: appsecret
      namespace: default
    type: Opaque
