---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: appsecret
  namespace: default
spec:
  encryptedData:
    apikey: AgB2LGMaIryrzLTBTSXjPkoRoLPxz22dpnlR1SsvIJbGXYmylQ0hBdrvHboDYXJydmwn5UB/D2HbkUx2XVoTfb0nf6p1xYZZDkOq4FOkfN6n72171vNDD9VRGRqDlWw76+U3e8PBYP5s4PfrdNqWgydllKAUCK9a5MoFCdFxeRbbkNWBc7Sr3BK7nHZBQiqoYeGQronh4jIuJQ3fEG9Goh9UTgDJGA9eQe5CBQol6nRP4phlnoS9Uvj62euh7oNwuFpySJUYiqM9wqoe6549bxzT02iZ97r7IcUSH0GNrI+LRIkJAj7ib8u5AiyrhFGrdUYfZ8YKwHYtsixMwVSYO3U+B+yuLl5C14xigrat3l0cuYaIqURGLQL76esfqdw44eaBUF3Ty5juvdAltpQkAmrpwbAg6VRXPn1eFSl+N7yyIGl9E5YCio1RXLaMO95Q3sueB5Lkh9+Le+r06+zvHfFsG0RnSseYclAtyLO//Ak2Lbh2U4B9BIXGe/TfJP68M1U9eXs50Do9vPLnuWMMl4IKkoPTfVYtwQNkgyriEPs7niM3tEq9lKCGSQohSQRmQknJmuvkkwC1au5e3rJeBNENoc/WhNorwztggytL6FHXa/WhQI5KGkPichlUcuCknIT9Y4T5YXw3/bNCN3mdo1rrr2bWEdxT6XYt+P7i7XOtQY2r7T9KOsmJ9fEoyR+nz+MgNZySCusbnUqnZEp/atgDMYz9AMWLbLNcx/K1T4dSN/LviMJ5CVA=
  template:
    metadata:
      creationTimestamp: null
      name: appsecret
      namespace: default
    type: Opaque
